---
- name: Common | Disable swap
  command: swapoff -a
  ignore_errors: yes

- name: Common | Disable swap permanently
  lineinfile:
    path: /etc/fstab
    regexp: '^/dev/mapper/.*swap'
    line: '#\0'
    backrefs: yes

- name: Common | Install dependencies
  apt:
    name: ["apt-transport-https", "ca-certificates", "curl", "gnupg",
           "software-properties-common"]
    update_cache: yes
    state: present

- name: Common | Add Docker GPG key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Common | Add Docker repository
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
    state: present

- name: Common | Install Docker
  apt:
    name: docker-ce
    state: present
    update_cache: yes

- name: Common | Ensure Docker is running and enabled
  systemd:
    name: docker
    state: started
    enabled: yes

- name: Common | Add Kubernetes GPG key
  apt_key:
    url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
    state: present

- name: Common | Add Kubernetes repository
  apt_repository:
    repo: "deb https://apt.kubernetes.io/ kubernetes-xenial main"
    state: present
    filename: kubernetes

- name: Common | Install kubelet, kubeadm and kubectl
  apt:
    name: ["kubelet={{ kube_version }}-00", "kubeadm={{ kube_version }}-00",
           "kubectl={{ kube_version }}-00"]
    state: present
    update_cache: yes

- name: Common | Hold kubelet, kubeadm and kubectl at current version
  command: apt-mark hold kubelet kubeadm kubectl

- name: Common | Configure sysctl
  sysctl:
    name: "{{ item.key }}"
    value: "{{ item.value }}"
    state: present
    reload: yes
  with_items:
    - { key: 'net.bridge.bridge-nf-call-iptables', value: '1' }
    - { key: 'net.bridge.bridge-nf-call-ip6tables', value: '1' }
    - { key: 'net.ipv4.ip_forward', value: '1' }
