# Daemon settings
config:
  core.https_address: 192.0.2.1:9999
  images.auto_update_interval: 6

storage_pools:
- name: data
  driver: zfs
  config:
    source: zfs-pool/zfs-dataset

storage_volumes:
- name: vol
  pool: data

networks:
- name: incus-bridge
  type: bridge
  config:
    ipv4.address: auto
    ipv6.address: none

profiles:
- name: default
  devices:
    root:
      path: /
      pool: data
      type: disk
- name: test-profile
  description: "Test profile"
  config:
    limits.memory: 2GiB
  devices:
    test0:
      name: test0
      nictype: bridged
      parent: incus-bridge
      type: nic
