apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: le-crt
spec:
  secretName: tls-secret-le
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt
  commonName: bergman-task-resolver-api.mfti.devops-teta.ru
  dnsNames:
  - bergman-task-resolver-api.mfti.devops-teta.ru
