---
- name: Set up Kubernetes multi-node cluster
  hosts: incus_vms
  become: yes
  gather_facts: yes
  roles:
    - common

- name: Configure Kubernetes master node
  hosts: master
  become: yes
  roles:
    - master

- name: Configure Kubernetes worker nodes
  hosts: workers
  become: yes
  roles:
    - worker
