---
- name: Set up Kubernetes multi-node cluster
  hosts: kube-cluster
  become: yes
  gather_facts: yes

  vars:
    kube_version: "1.28.0"
    pod_network_cidr: "10.244.0.0/16"
    service_cidr: "10.96.0.0/12"

  roles:
    - common

- name: Configure Kubernetes master node
  hosts: master
  become: yes
  roles:
    - master

- name: Configure Kubernetes worker nodes
  hosts: workers
  become: yes
  roles:
    - worker
