apiVersion: v1
data:
  agent-config.yaml: |
    kafka:
      addr: kafka-cluster:9092
      group: agent-group
      task_topic: tasks
      status_topic: task-status
    data-provider:
      addr: http://data-provider:8080
    agent:
      http:
        addr: 0.0.0.0:8080
kind: ConfigMap
metadata:
  annotations:
    use-subpath: "true"
  labels:
    io.kompose.service: agent
  name: agent-cm0
