apiVersion: v1
data:
  api-config.yaml: |-
    api-service:
      http:
        addr: 0.0.0.0:8080
    agent:
      addr: http://agent:8080
    data-provider:
      addr: http://data-provider:8080
kind: ConfigMap
metadata:
  annotations:
    use-subpath: "true"
  labels:
    io.kompose.service: api
  name: api-cm0
