apiVersion: v1
data:
  worker-config.yaml: |
    http:
      addr: 0.0.0.0:8080

    kafka:
      addr: kafka-svc:9092
      group: ""
      task_topic: tasks
      status_topic: task-status

    worker:
      queue_size: 2
      threads: 2
kind: ConfigMap
metadata:
  annotations:
    use-subpath: "true"
  labels:
    io.kompose.service: worker
  name: worker-cm0
