apiVersion: v1
data:
  worker-config.yaml: |
    kafka:
      addr: kafka-cluster:9092
      group: worker-group
      task_topic: tasks
      status_topic: task-status
      timeout: 10s
      retries: 3

    worker:
      timescale: 1s
kind: ConfigMap
metadata:
  annotations:
    use-subpath: "true"
  labels:
    io.kompose.service: worker
  name: worker-cm0
