---
- name: Master | Initialize Kubernetes cluster
  command: >
    kubeadm init
      --pod-network-cidr={{ pod_network_cidr }}
      --service-cidr={{ service_cidr }}
      --ignore-preflight-errors=Swap
  register: kubeadm_init

- name: Master | Create .kube directory
  file:
    path: /root/.kube
    state: directory
    mode: 0755

- name: Master | Copy admin.conf to user config
  copy:
    src: /etc/kubernetes/admin.conf
    dest: /root/.kube/config
    remote_src: yes
    owner: root
    group: root
    mode: 0600

- name: Master | Install Pod network (Flannel)
  command: kubectl apply -f https://raw.githubusercontent.com/flannel-io/flannel/master/Documentation/kube-flannel.yml
  when: inventory_hostname in groups['master'][0]

- name: Master | Generate join command
  command: kubeadm token create --print-join-command
  register: join_command
  # when: inventory_hostname in groups['master'][0]

- name: Master | Get pwd
  set_fact:
    _pwd: "{{ lookup('env', 'PWD') }}"

- name: Master | Save join command to local file
  local_action:
    module: copy
    content: "{{ join_command.stdout }}"
    dest: "{{ _pwd }}/generated/k8s-join-command.txt"
  # when: inventory_hostname in groups['master'][0]
