apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: certs
  name: certs
spec:
  storageClassName: nfs-csi
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
