---
- name: Kubernetes Common | Disable swap
  command: swapoff -a
  ignore_errors: yes

- name: Kubernetes Common | Disable swap permanently
  lineinfile:
    path: /etc/fstab
    regexp: '^/dev/mapper/.*swap'
    line: '#\0'
    backrefs: yes

- name: Kubernetes Common | Install dependencies
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg
      - lsb-release
      - software-properties-common
    update_cache: yes
    state: present

- name: Kubernetes Common | Add Docker GPG key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Kubernetes Common | Get container arhitecture
  block:
    - shell: dpkg --print-architecture
      register: _arch_raw

    - set_fact:
        _arch: "{{ _arch_raw.stdout | trim }}"

- name: Kubernetes Common | Add Docker repository
  apt_repository:
    repo: "deb [arch={{ _arch }} signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
    state: present
    update_cache: yes

- name: Kubernetes Common | Install Docker
  apt:
    name: 
      - docker-ce
      - docker-ce-cli
      - containerd.io
    state: present
    update_cache: yes

- name: Kubernetes Common | Ensure Docker is running and enabled
  systemd:
    name: docker
    state: started
    enabled: yes

- name: Kubernetes Common | Add Kubernetes GPG key
  apt_key:
    url: "https://pkgs.k8s.io/core:/stable:/v{{ kube_version.split('.')[0] }}.{{ kube_version.split('.')[1] }}/deb/Release.key"
    state: present

- name: Kubernetes Common | Add Kubernetes repository
  apt_repository:
    repo: "deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v{{ kube_version.split('.')[0] }}.{{ kube_version.split('.')[1] }}/deb/ /"
    state: present
    update_cache: yes

- name: Kubernetes Common | Install kubelet, kubeadm and kubectl
  apt:
    name:
      - "kubelet={{ kube_version }}-00"
      - "kubeadm={{ kube_version }}-00"
      - "kubectl={{ kube_version }}-00"
    state: present
    update_cache: yes

- name: Kubernetes Common | Hold kubelet, kubeadm and kubectl at current version
  command: apt-mark hold kubelet kubeadm kubectl

- name: Kubernetes Common | Configure sysctl
  sysctl:
    name: "{{ item.key }}"
    value: "{{ item.value }}"
    state: present
    reload: yes
  with_items:
    - { key: 'net.bridge.bridge-nf-call-iptables', value: '1' }
    - { key: 'net.bridge.bridge-nf-call-ip6tables', value: '1' }
    - { key: 'net.ipv4.ip_forward', value: '1' }
