apiVersion: apps/v1
kind: Job
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yaml -o /tmp/k8s/
    kompose.version: 1.35.0 (HEAD)
  labels:
    io.kompose.service: certificate-generator
  name: certificate-generator
spec:
  replicas: 1
  ttlSecondsAfterFinished: 60
  selector:
    matchLabels:
      io.kompose.service: certificate-generator
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yaml -o /tmp/k8s/
        kompose.version: 1.35.0 (HEAD)
      labels:
        io.kompose.service: certificate-generator
    spec:
      containers:
        - args:
            - /configs
            - /certs
            - api-service
            - agent-service
            - data-provider-service
          image: certificate-generator
          name: certificate-generator
          volumeMounts:
            - mountPath: /configs
              name: certs-configs
            - mountPath: /certs
              name: certs
      restartPolicy: OnFailure
      volumes:
        - name: certs
          persistentVolumeClaim:
            claimName: certs
        - name: certs-configs
          configMap:
            name: certs-configs
            items:
              - key: internal-ca.conf
                path: internal/internal-ca.conf
              - key: root-ca.conf
                path: root/root-ca.conf
              - key: agent-service.conf
                path: services/agent-service.conf
              - key: api-service.conf
                path: services/api-service.conf
              - key: data-provider-service.conf
                path: services/data-provider-service.conf
